import { Inter } from 'next/font/google'
import './globals.css'
import { GoogleOAuthProvider } from '@react-oauth/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Chintu AI',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><GoogleOAuthProvider clientId={process.env.clientID}>
        {children}
      </GoogleOAuthProvider></body>
    </html>
  )
}
